---
title: "Lab 3"
author: "Corinna Hong"
date: "January 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE)
```

```{r, load packages}

library(tidyverse)
library(janitor)
library(here)
library(sf)
library(tmap)

```

# Binary Logicist Regression - Penguins

```{r, get data set ready}

chinstrap <- read_csv("chinstrap_lter.csv")
gentoo <- read_csv("gentoo_lter.csv")

penguins <- full_join(chinstrap,gentoo) %>% 
  clean_names() %>% 
  mutate(sex = str_to_lower(sex)) %>% # mutate here overrides current column, changes strint to lowercase in sex column
  filter(sex %in% c("male", "female")) # look for anything in sex column that matching anything in this string

```

```{r, visualize data}

ggplot(data = penguins, aes(x = sex, y = body_mass_g)) +
  geom_jitter(aes(color = sex, pch = sex)) + # change color and point type to differ by sex
  facet_wrap(~species) +
  theme_minimal()

```

```{r, assign each species a binary code}

penguin_bin <- penguins %>% 
  mutate(
    sp_binary = case_when(
      species == "Gentoo penguin (Pygoscelis papua)" ~ 0,
      species == "Chinstrap penguin (Pygoscelis antarctica)" ~ 1
    )
  )

```

```{r, binary logistic regression}

penguin_blr <- glm(sp_binary ~ sex + body_mass_g, family = binomial, data = penguin_bin)

summary(penguin_blr)

# b/c chinstrap is coded as 1, the blr results describe the variables' impacts on probabiliy of being a chinstrap

```

### Make predictions for penguins

a. What is the probably that the penguin is a Chinstrap penguin if it weighs 4500g and is male?

```{r, new df that contains only the things we are interested in}

df_m4500 <- data.frame(sex = "male", body_mass_g = 4500)

# find log odds of this penguin being Chinstrap
m4500_logodds <- predict(penguin_blr, newdata = df_m4500, type = "link") # log odds of 4.05

# find probabily of this penguin being chinstrap
m4500_prob <- predict(penguin_blr, newdata = df_m4500, type = "response") # probability of 0.98 

```

b. What is the probability that a penguin is a Chinstrap penguin if it weighs 4000g and is female?

```{r}

df_f4000 <- data.frame(sex = "female", body_mass_g = 4000)

# find log odds of this penguin being Chinstrap
f4000_logodds <- predict(penguin_blr, newdata = df_f4000, type = "link") # log odds of 0.637

# find probabily of this penguin being chinstrap
f4000_prob <- predict(penguin_blr, newdata = df_f4000, type = "response") # probability of 0.65

```

c. Make an entire df and use it to make, then visualize, logistic regression outcomes

```{r}

penguins_mock <- data.frame(
  body_mass_g = rep(seq(3000, 6000, length = 200),2),
  sex = c(rep("male", 200), rep("female",200))
  )

```

```{r, getting probabilities for made up dataframe}

# create list of probabilities and standard errors
full_predict <- predict(penguin_blr, newdata = penguins_mock, type = "response", se.fit = TRUE)

# get these predictions into penguins mock data frame
final_df <- data.frame(penguins_mock, full_predict$fit, full_predict$se.fit)

# renames columns for ease
colnames(final_df) <- c("penguin_mass", "sex", "probability", "se")

```

```{r, graph of predicted probabilities and their standard errors}

ggplot(data = final_df, aes(x = penguin_mass, y = probability)) +
  geom_line(aes(color = sex)) +
  geom_ribbon(aes(ymin = probability - se, ymax = probability + se, fill = sex), alpha = 0.3) +
  theme_minimal()

```

# Spatial data

```{r, read in spatial data}

cougars <- read_sf(dsn = here("cougar_connections"),layer = "ds1014") %>% 
  clean_names()

```

```{r, keep larger corridors}

large_corridors <- cougars %>% 
  filter(area_ac > 20000) %>% 
  select(area_ac)

plot(large_corridors)

```

```{r, make a subest of elevation data}

cougar_sub <- cougars %>% 
  select(elev_mean)

# plot it
ggplot(data = cougar_sub) +
  geom_sf(aes(fill  = elev_mean), color = NA)

```

```{r, put an interactive base map}

tmap_mode("view")

tm_shape(cougar_sub) +
  tm_fill("elev_mean")

```

